# PIAIC54482 Muhammad Sohail

In [39]:
import numpy as np

In [40]:
IstArr=[1,2.0,"Waqas", True]

In [41]:
SecArr=[[1, 2, 3], [4, 5, 6],[7,8,9]]

1. np.array

In [42]:
ar = np.array(IstArr)
ar

array(['1', '2.0', 'Waqas', 'True'], dtype='<U32')

In [43]:
ar2=np.array(SecArr)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2.shape

In [44]:
ar.shape

(4,)

In [45]:
ar2.shape

(3, 3)

3.type

In [46]:
type(ar)

numpy.ndarray

In [47]:
type(ar2)

numpy.ndarray

4.ar.dtype

In [48]:
ar.dtype

dtype('<U32')

In [49]:
ar2.dtype

dtype('int32')

5. The element of array

In [51]:
ar[1]

'2.0'

In [52]:
ar2[2]

array([7, 8, 9])

6. slicing

In [53]:
ar2[1:,1]

array([5, 8])

In [54]:
ar2[:,1]

array([2, 5, 8])

7.flags

In [55]:
ar.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

7.strides

In [56]:
ar.strides

(128,)

In [57]:
ar2.strides

(12, 4)

8.dimensions

In [58]:
ar.ndim

1

In [59]:
ar2.ndim

2

9. data

In [62]:
ar.data

In [63]:
ar2.data

10.Size

In [66]:
ar2.size

9

In [67]:
ar.size

4

11. itemsize

In [68]:
ar.itemsize

128

In [69]:
ar2.itemsize

4

12.bytes

In [70]:
ar.nbytes

512

In [71]:
ar2.nbytes

36

13.base objects

In [74]:
ar2.base

14. transpose

In [75]:
ar.T

array(['1', '2.0', 'Waqas', 'True'], dtype='<U32')

In [76]:
ar2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

15. Real

In [77]:
ar.real

array(['1', '2.0', 'Waqas', 'True'], dtype='<U32')

In [78]:
ar2.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

16. image

In [80]:
ar.imag

array(['', '', '', ''], dtype='<U32')

In [81]:
ar2.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

17. flat

In [82]:
ar.flat

In [83]:
ar2.flat

18. ctypes

In [84]:
ar.ctypes

In [85]:
ar2.ctypes

19. item

In [90]:
ar.item(2)

'Waqas'

In [91]:
ar2.item(3)

4

20. list

In [93]:
lst=list(ar)

In [94]:
type(lst)

list

In [95]:
lst

['1', '2.0', 'Waqas', 'True']

21. itemset

In [100]:
ar2.itemset(1,2)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
ar2.itemset(2,4)

In [102]:
ar2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

22. tobytes

In [104]:
ar.tobytes()

b'1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x002\x00\x00\x00.\x00\x00\x000\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x

In [105]:
ar.tostring()

b'1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x002\x00\x00\x00.\x00\x00\x000\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x

In [106]:
ar

array(['1', '2.0', '4', 'True'], dtype='<U32')

In [107]:
ar2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

23. astype

In [112]:
ar.astype(str)

array(['1', '2.0', '4', 'True'], dtype='<U32')

In [113]:
type(ar)

numpy.ndarray

24.byteswap

In [115]:
ar.byteswap

<function ndarray.byteswap>

In [116]:
ar

array(['1', '2.0', '4', 'True'], dtype='<U32')

25. Copy

In [117]:
ar2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
ar3=ar2.copy()

In [119]:
ar3

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
ar2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

26. fill

In [122]:
ar2.fill(0)

In [123]:
ar2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

27. view

In [127]:
ar.view()

array(['1', '2.0', '4', 'True'], dtype='<U32')

28. Reshape

In [143]:
ar2=([[0, 1],
       [2, 3],
       [4, 5]])

In [144]:
np.shape(ar2)

(3, 2)

In [150]:
np.reshape(ar3,(3,3))
ar3

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
np.shape(ar2)

(3, 2)

In [154]:
np.reshape(ar3,9)

array([1, 2, 4, 4, 5, 6, 7, 8, 9])

29. resize

In [163]:
ar4=np.array([[0, 1], [2, 3]], order='C')
ar4.resize((2, 1))

In [164]:
ar4

array([[0],
       [1]])

30. transpose

In [165]:
ar3

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
ar3.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [4, 6, 9]])

31. swapaxes

In [170]:
np.swapaxes(ar3,1,1)

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

32. flattern

In [172]:
ar3.flatten()

array([1, 2, 4, 4, 5, 6, 7, 8, 9])

33. ravel

In [175]:
ar3.ravel(order='F')

array([1, 4, 7, 2, 5, 8, 4, 6, 9])

34. squeez

In [176]:
ar3.squeeze()

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

35. sort

In [194]:
ar3=[[1,4], [3,1]]

In [199]:
a = np.array([[1,4], [3,1]])
a.sort(axis=1)
a

array([[1, 4],
       [1, 3]])

36. argsort

In [202]:
x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [204]:
ind = np.argsort(x, axis=0)
ind

array([[0, 1],
       [1, 0]], dtype=int64)

37. nonezero

In [205]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x

array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

In [209]:
np.nonzero(x)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

38. compress

In [212]:
np.compress([True,True],ar3)

array([1, 4])

In [213]:
ar3

[[1, 4], [3, 1]]

39.diagnal

In [218]:
ar4

array([[0],
       [1]])

In [219]:
ar4.diagonal()

array([0])

40.amax

In [221]:
ar2

[[0, 1], [2, 3], [4, 5]]

In [223]:
np.amax(ar2)

5

41. min

In [224]:
np.amin(ar2)

0

42. sum

In [225]:
np.sum(ar2)

15

43. mean

In [226]:
np.mean(ar2)

2.5

44.isdecimal()

In [231]:
ar.isdecimal()

AttributeError: 'numpy.ndarray' object has no attribute 'isdecimal'

45. count

In [233]:
a = np.array(['aAaAaA', '  aA  ', 'abBABba'])
a

array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')

In [235]:
np.char.count(a, 'b')

array([0, 0, 2])

In [236]:
np.char.count(a, 'B')

array([0, 0, 2])

In [237]:
np.char.count(a, 'a')

array([3, 1, 2])

46.endswith

In [239]:
np.char.endswith(a, 'a')

array([False, False,  True])

47. find

In [250]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


48. searchsorted

In [252]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


49. filter

In [253]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


50. random

In [256]:
from numpy import random
x = random.randint(100)
print(x)

33


51. ufunc

In [257]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


End