# PIAIC54482 Muhammad Sohail

In [39]:
import numpy as np

In [40]:
IstArr=[1,2.0,"Waqas", True]

In [41]:
SecArr=[[1, 2, 3], [4, 5, 6],[7,8,9]]

1. np.array

In [42]:
ar = np.array(IstArr)
ar

array(['1', '2.0', 'Waqas', 'True'], dtype='<U32')

In [43]:
ar2=np.array(SecArr)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2.shape

In [44]:
ar.shape

(4,)

In [45]:
ar2.shape

(3, 3)

3.type

In [46]:
type(ar)

numpy.ndarray

In [47]:
type(ar2)

numpy.ndarray

4.ar.dtype

In [48]:
ar.dtype

dtype('<U32')

In [49]:
ar2.dtype

dtype('int32')

5. The element of array

In [51]:
ar[1]

'2.0'

In [52]:
ar2[2]

array([7, 8, 9])

6. slicing

In [53]:
ar2[1:,1]

array([5, 8])

In [54]:
ar2[:,1]

array([2, 5, 8])

7.flags

In [55]:
ar.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

7.strides

In [56]:
ar.strides

(128,)

In [57]:
ar2.strides

(12, 4)

8.dimensions

In [58]:
ar.ndim

1

In [59]:
ar2.ndim

2

9. data

In [62]:
ar.data

In [63]:
ar2.data

10.Size

In [66]:
ar2.size

9

In [67]:
ar.size

4

11. itemsize

In [68]:
ar.itemsize

128

In [69]:
ar2.itemsize

4

12.bytes

In [70]:
ar.nbytes

512

In [71]:
ar2.nbytes

36

13.base objects

In [74]:
ar2.base

14. transpose

In [75]:
ar.T

array(['1', '2.0', 'Waqas', 'True'], dtype='<U32')

In [76]:
ar2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

15. Real

In [77]:
ar.real

array(['1', '2.0', 'Waqas', 'True'], dtype='<U32')

In [78]:
ar2.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

16. image

In [80]:
ar.imag

array(['', '', '', ''], dtype='<U32')

In [81]:
ar2.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

17. flat

In [82]:
ar.flat

In [83]:
ar2.flat

18. ctypes

In [84]:
ar.ctypes

In [85]:
ar2.ctypes

19. item

In [90]:
ar.item(2)

'Waqas'

In [91]:
ar2.item(3)

4

20. list

In [93]:
lst=list(ar)

In [94]:
type(lst)

list

In [95]:
lst

['1', '2.0', 'Waqas', 'True']

21. itemset

In [100]:
ar2.itemset(1,2)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
ar2.itemset(2,4)

In [102]:
ar2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

22. tobytes

In [104]:
ar.tobytes()

b'1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x002\x00\x00\x00.\x00\x00\x000\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x

In [105]:
ar.tostring()

b'1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x002\x00\x00\x00.\x00\x00\x000\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x

In [106]:
ar

array(['1', '2.0', '4', 'True'], dtype='<U32')

In [107]:
ar2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

23. astype

In [112]:
ar.astype(str)

array(['1', '2.0', '4', 'True'], dtype='<U32')

In [113]:
type(ar)

numpy.ndarray

24.byteswap

In [115]:
ar.byteswap

<function ndarray.byteswap>

In [116]:
ar

array(['1', '2.0', '4', 'True'], dtype='<U32')

25. Copy

In [117]:
ar2

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
ar2