In [1]:
import numpy as np

In [2]:
l=range(100000)

In [3]:
l

range(0, 100000)

In [2]:
d=np.arange(100000)

NameError: name 'np' is not defined

In [6]:
d

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [14]:
%time  for i in range(0,10): r=[x*2 for x in l]
print(i)

Wall time: 88 ms
9


In [1]:
x=np.zeros((5,4))
x

NameError: name 'np' is not defined

In [20]:
y=np.empty((4,4))
y

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06811083e-306],
       [6.23057349e-307, 2.22522597e-306, 1.33511969e-306,
        1.37962320e-306],
       [9.34604358e-307, 9.79101082e-307, 1.78020576e-306,
        1.69119873e-306],
       [2.22522868e-306, 1.24611809e-306, 8.06632139e-308,
        1.60221208e-306]])

In [21]:
z=np.ones((5,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.array(l)

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [26]:
np.arange(1,100,5) #5 is step size

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [28]:
x.shape

(4, 4)

In [36]:
x=np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
y=x.reshape((2,2,5,5))
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [42]:
z=x.reshape(())
z

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0.,

In [44]:
z.shape

(5, 5, 2, 2)

In [45]:
a=np.random.rand(10)
a

array([0.15759414, 0.37782458, 0.19370718, 0.48016301, 0.94490237,
       0.53347438, 0.7624871 , 0.79579824, 0.7795716 , 0.31593138])

In [46]:
b=np.random.rand(10)
b

array([0.96718109, 0.62531643, 0.64183507, 0.72874539, 0.7056673 ,
       0.84033462, 0.94058999, 0.17406515, 0.09108669, 0.71023228])

In [47]:
a+b

array([1.12477523, 1.00314101, 0.83554224, 1.20890841, 1.65056967,
       1.373809  , 1.70307708, 0.9698634 , 0.87065829, 1.02616367])

In [48]:
a+b+b

array([2.09195633, 1.62845745, 1.47737731, 1.9376538 , 2.35623697,
       2.21414362, 2.64366707, 1.14392855, 0.96174498, 1.73639595])

In [49]:
a>0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [50]:
b

array([0.96718109, 0.62531643, 0.64183507, 0.72874539, 0.7056673 ,
       0.84033462, 0.94058999, 0.17406515, 0.09108669, 0.71023228])

In [51]:
a>0.5

array([False, False, False, False,  True,  True,  True,  True,  True,
       False])

In [52]:
a[a>0.5]

array([0.94490237, 0.53347438, 0.7624871 , 0.79579824, 0.7795716 ])

In [62]:
a[[2,3]]

array([0.19370718, 0.48016301])

In [63]:
b=np.random.randn(10,10)

In [66]:
b[1,3]

-0.2955062540113488

In [69]:
a[1:-1]

array([0.37782458, 0.19370718, 0.48016301, 0.94490237, 0.53347438,
       0.7624871 , 0.79579824, 0.7795716 ])

In [70]:
a

array([0.15759414, 0.37782458, 0.19370718, 0.48016301, 0.94490237,
       0.53347438, 0.7624871 , 0.79579824, 0.7795716 , 0.31593138])

In [71]:
c=np.random.rand((10))

In [72]:
c

array([0.73572832, 0.08226013, 0.63073089, 0.216543  , 0.55022641,
       0.62337142, 0.90402807, 0.84755173, 0.41433594, 0.62042392])

In [73]:
c[1]

0.08226013465151327

In [78]:
d=np.random.rand(10,10)
d

array([[0.87064295, 0.38642985, 0.37290811, 0.24429614, 0.91110776,
        0.27680572, 0.58264952, 0.87788089, 0.27708766, 0.70894525],
       [0.74675738, 0.90398806, 0.58966268, 0.84372723, 0.92475613,
        0.22679016, 0.7538938 , 0.6966193 , 0.59180875, 0.0829389 ],
       [0.67304196, 0.78054945, 0.39531687, 0.96666642, 0.27581413,
        0.00637395, 0.51408703, 0.20477539, 0.37393795, 0.21389097],
       [0.09928658, 0.39163598, 0.49972017, 0.23798125, 0.71939201,
        0.93240485, 0.81579696, 0.90803507, 0.28358566, 0.50233642],
       [0.2332428 , 0.44695216, 0.51736361, 0.6782753 , 0.24523162,
        0.69927847, 0.59348413, 0.35134565, 0.79149359, 0.29970882],
       [0.09643288, 0.78584882, 0.98011601, 0.24651236, 0.45791751,
        0.27850085, 0.65478369, 0.83967142, 0.71773453, 0.31895644],
       [0.90717617, 0.42198104, 0.84722094, 0.47726857, 0.98429829,
        0.23984828, 0.29830124, 0.37825739, 0.32954088, 0.85096402],
       [0.62240589, 0.88003752, 0.2258610

In [76]:
e=np.array((10,10))

In [77]:
e

array([10, 10])

In [82]:
np.where(d>=0.6,1,d)
d

array([[0.87064295, 0.38642985, 0.37290811, 0.24429614, 0.91110776,
        0.27680572, 0.58264952, 0.87788089, 0.27708766, 0.70894525],
       [0.74675738, 0.90398806, 0.58966268, 0.84372723, 0.92475613,
        0.22679016, 0.7538938 , 0.6966193 , 0.59180875, 0.0829389 ],
       [0.67304196, 0.78054945, 0.39531687, 0.96666642, 0.27581413,
        0.00637395, 0.51408703, 0.20477539, 0.37393795, 0.21389097],
       [0.09928658, 0.39163598, 0.49972017, 0.23798125, 0.71939201,
        0.93240485, 0.81579696, 0.90803507, 0.28358566, 0.50233642],
       [0.2332428 , 0.44695216, 0.51736361, 0.6782753 , 0.24523162,
        0.69927847, 0.59348413, 0.35134565, 0.79149359, 0.29970882],
       [0.09643288, 0.78584882, 0.98011601, 0.24651236, 0.45791751,
        0.27850085, 0.65478369, 0.83967142, 0.71773453, 0.31895644],
       [0.90717617, 0.42198104, 0.84722094, 0.47726857, 0.98429829,
        0.23984828, 0.29830124, 0.37825739, 0.32954088, 0.85096402],
       [0.62240589, 0.88003752, 0.2258610

In [84]:
a

array([0.15759414, 0.37782458, 0.19370718, 0.48016301, 0.94490237,
       0.53347438, 0.7624871 , 0.79579824, 0.7795716 , 0.31593138])

In [88]:
np.where(a>=0.7624871,1,a)

array([0.15759414, 0.37782458, 0.19370718, 0.48016301, 1.        ,
       0.53347438, 0.7624871 , 1.        , 1.        , 0.31593138])

In [86]:
sal=np.array([0,-1,100000])

In [90]:
sal=np.where(sal<=0,25000,sal)

In [91]:
sal

array([ 25000,  25000, 100000])

In [92]:
sal

array([ 25000,  25000, 100000])

In [93]:
sal.mean()

50000.0

In [94]:
sal.cumsum()

array([ 25000,  50000, 150000], dtype=int32)

In [96]:
sal.cumprod()


array([     25000,  625000000, -364091392], dtype=int32)

In [99]:
x=np.random.seed(1)

In [103]:
x=np.random.uniform(size=(3,3))

In [104]:
x

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01]])

In [111]:
x=np.random.normal(size=(4,3))

In [112]:
x

array([[-0.56651023,  0.7299756 ,  0.37299379],
       [ 0.53381091, -0.0919733 ,  1.91382039],
       [ 0.33079713,  1.14194252, -1.12959516],
       [-0.85005238,  0.96082   , -0.21741818]])

In [113]:
x.reshape(2,2,3)

array([[[-0.56651023,  0.7299756 ,  0.37299379],
        [ 0.53381091, -0.0919733 ,  1.91382039]],

       [[ 0.33079713,  1.14194252, -1.12959516],
        [-0.85005238,  0.96082   , -0.21741818]]])

In [115]:
x.reshape(3,4,-1)

array([[[-0.56651023],
        [ 0.7299756 ],
        [ 0.37299379],
        [ 0.53381091]],

       [[-0.0919733 ],
        [ 1.91382039],
        [ 0.33079713],
        [ 1.14194252]],

       [[-1.12959516],
        [-0.85005238],
        [ 0.96082   ],
        [-0.21741818]]])

In [116]:
x.flatten()

array([-0.56651023,  0.7299756 ,  0.37299379,  0.53381091, -0.0919733 ,
        1.91382039,  0.33079713,  1.14194252, -1.12959516, -0.85005238,
        0.96082   , -0.21741818])

In [117]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [118]:
x

array([[-0.56651023,  0.7299756 ,  0.37299379],
       [ 0.53381091, -0.0919733 ,  1.91382039],
       [ 0.33079713,  1.14194252, -1.12959516],
       [-0.85005238,  0.96082   , -0.21741818]])

In [119]:
y=x.copy()

In [120]:
y

array([[-0.56651023,  0.7299756 ,  0.37299379],
       [ 0.53381091, -0.0919733 ,  1.91382039],
       [ 0.33079713,  1.14194252, -1.12959516],
       [-0.85005238,  0.96082   , -0.21741818]])

In [ ]:
x